package app

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInitCreatesCompleteProjectWithoutAIGuideByDefault(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	for _, name := range []string{"nodepaper.yaml", "paper.md", "references.bib", ".gitignore"} {
		if _, err := os.Stat(filepath.Join(projectDir, name)); err != nil {
			t.Fatalf("%s: %v", name, err)
		}
	}
	if info, err := os.Stat(filepath.Join(projectDir, "images")); err != nil || !info.IsDir() {
		t.Fatalf("images: info=%v err=%v", info, err)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Fatalf("AGENTS.md should not be generated by default; err=%v", err)
	}
}

func TestInitAIGuideContainsRequiredSafetyBoundaries(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "中文 project")
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{"nodepaper.yaml", "Front Matter", "references.bib", "#fig:result", "不得猜造", "不执行", "nodepaper validate", "nodepaper build"} {
		if !strings.Contains(string(content), required) {
			t.Errorf("AGENTS.md missing %q", required)
		}
	}
}

func TestInitPreservesExistingAIGuide(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	const original = "user-owned guide\n"
	if err := os.WriteFile(filepath.Join(projectDir, "AGENTS.md"), []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != original {
		t.Fatalf("AGENTS.md = %q, want preserved %q", content, original)
	}
	if len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeAIGuidePreserved {
		t.Fatalf("diagnostics = %#v, want %s", result.Diagnostics, codeAIGuidePreserved)
	}
}

func TestInitRefusesToOverwriteAndLeavesExistingDirectoryUnchanged(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	const original = "existing paper\n"
	if err := os.WriteFile(filepath.Join(projectDir, "paper.md"), []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir})
	if err != nil {
		t.Fatal(err)
	}
	if result.Success || len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeInitWouldOverwrite {
		t.Fatalf("result = %#v, want %s", result, codeInitWouldOverwrite)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "paper.md"))
	if err != nil || string(content) != original {
		t.Fatalf("paper.md changed: content=%q err=%v", content, err)
	}
	for _, name := range []string{"nodepaper.yaml", "references.bib", ".gitignore", "images"} {
		if _, err := os.Stat(filepath.Join(projectDir, name)); !os.IsNotExist(err) {
			t.Fatalf("partial initialization left %s; err=%v", name, err)
		}
	}
}

func TestInitCanceledBeforeStartLeavesNoProject(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	result, err := (&appImpl{}).Init(ctx, InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.Success || len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeInitCanceled {
		t.Fatalf("result = %#v, want %s", result, codeInitCanceled)
	}
	if _, err := os.Stat(projectDir); !os.IsNotExist(err) {
		t.Fatalf("canceled init left a Project directory; err=%v", err)
	}
}
