package app

import (
	"context"
	"nodepaper/internal/config"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestInitCreatesCompleteProjectWithoutAIGuideByDefault(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	for _, name := range []string{"nodepaper.yaml", "paper.md", "ai-usage.md", "references.bib", ".gitignore"} {
		if _, err := os.Stat(filepath.Join(projectDir, name)); err != nil {
			t.Fatalf("%s: %v", name, err)
		}
	}
	if info, err := os.Stat(filepath.Join(projectDir, "images")); err != nil || !info.IsDir() {
		t.Fatalf("images: info=%v err=%v", info, err)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "AGENTS.md")); !os.IsNotExist(err) {
		t.Fatalf("AGENTS.md should not be generated by default; err=%v", err)
	}
}

func TestInitShipsTheAIStatementDisabled(t *testing.T) {
	// Every Project gets the Markdown, so a team that starts using an AI tool
	// mid-competition has the template at hand. Nothing is built until the
	// author uncomments the configuration line: a team that used no AI tool
	// must not hand in a supporting document it never needed.
	projectDir := filepath.Join(t.TempDir(), "project")
	if _, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir}); err != nil {
		t.Fatal(err)
	}

	configText := readFile(t, filepath.Join(projectDir, "nodepaper.yaml"))
	if !strings.Contains(configText, "# aiStatement: ai-usage.md") {
		t.Fatalf("nodepaper.yaml does not carry the commented aiStatement line:\n%s", configText)
	}
	for _, line := range strings.Split(configText, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "aiStatement:") {
			t.Fatalf("nodepaper.yaml enables aiStatement by default: %q", line)
		}
	}

	statement := readFile(t, filepath.Join(projectDir, "ai-usage.md"))
	// The sections mirror the four items 《人工智能工具使用规定（2026 年试行）》
	// 第 4 条 asks the supporting document to cover.
	for _, required := range []string{
		"title: AI工具使用详情",
		"# 工具清单",
		"# 使用目的与环节",
		"# 提示方式与使用过程",
		"# 采纳、修改与核验",
	} {
		if !strings.Contains(statement, required) {
			t.Fatalf("ai-usage.md is missing %q:\n%s", required, statement)
		}
	}
	// 2025 asked for verbatim interaction records and for AI-generated content
	// to be marked in the body. 2026 asks for neither, and a template that
	// still demanded them would push teams past what the rules require.
	for _, gone := range []string{"# 关键交互记录", "正文相应位置标注"} {
		if strings.Contains(statement, gone) {
			t.Fatalf("ai-usage.md still carries the superseded 2025 requirement %q", gone)
		}
	}
}

func TestInitDeclaresNoAIToolUseByDefault(t *testing.T) {
	// aiUsage has no default in the config loader - an unset value is refused
	// rather than read as none - so init has to write one, and the safe default
	// is the declaration the majority of teams need.
	projectDir := filepath.Join(t.TempDir(), "project")
	if _, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir}); err != nil {
		t.Fatal(err)
	}

	// Parsing rather than string matching: what matters is the value the loader
	// reads, not the shape of the line it came from.
	cfg, err := config.Load(filepath.Join(projectDir, "nodepaper.yaml"))
	if err != nil {
		t.Fatalf("the generated config does not load: %v", err)
	}
	if cfg.AIUsage == nil || *cfg.AIUsage {
		t.Fatalf("nodepaper.yaml does not declare aiUsage: false; got %v", cfg.AIUsage)
	}
	if cfg.AIUsagePurpose != "" {
		t.Fatalf("a Project that used no AI tool must ship no purpose; got %q", cfg.AIUsagePurpose)
	}

	// The declaration is generated in front of the references, so the paper
	// template has to give the filter that anchor to sit in front of.
	paper := readFile(t, filepath.Join(projectDir, "paper.md"))
	if !strings.Contains(paper, "# 参考文献") || !strings.Contains(paper, "::: {#refs}") {
		t.Fatalf("paper.md does not carry the references section and its refs div:\n%s", paper)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestInitAIGuideContainsRequiredSafetyBoundaries(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "中文 project")
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{"nodepaper.yaml", "Front Matter", "references.bib", "#fig:result", "不得猜造", "不执行", "nodepaper validate", "nodepaper build"} {
		if !strings.Contains(string(content), required) {
			t.Errorf("AGENTS.md missing %q", required)
		}
	}
}

func TestInitPreservesExistingAIGuide(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	const original = "user-owned guide\n"
	if err := os.WriteFile(filepath.Join(projectDir, "AGENTS.md"), []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Success {
		t.Fatalf("result = %#v", result)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "AGENTS.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != original {
		t.Fatalf("AGENTS.md = %q, want preserved %q", content, original)
	}
	if len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeAIGuidePreserved {
		t.Fatalf("diagnostics = %#v, want %s", result.Diagnostics, codeAIGuidePreserved)
	}
}

func TestInitRefusesToOverwriteAndLeavesExistingDirectoryUnchanged(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		t.Fatal(err)
	}
	const original = "existing paper\n"
	if err := os.WriteFile(filepath.Join(projectDir, "paper.md"), []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	result, err := (&appImpl{}).Init(context.Background(), InitRequest{ProjectDir: projectDir})
	if err != nil {
		t.Fatal(err)
	}
	if result.Success || len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeInitWouldOverwrite {
		t.Fatalf("result = %#v, want %s", result, codeInitWouldOverwrite)
	}
	content, err := os.ReadFile(filepath.Join(projectDir, "paper.md"))
	if err != nil || string(content) != original {
		t.Fatalf("paper.md changed: content=%q err=%v", content, err)
	}
	for _, name := range []string{"nodepaper.yaml", "references.bib", ".gitignore", "images"} {
		if _, err := os.Stat(filepath.Join(projectDir, name)); !os.IsNotExist(err) {
			t.Fatalf("partial initialization left %s; err=%v", name, err)
		}
	}
}

func TestInitCanceledBeforeStartLeavesNoProject(t *testing.T) {
	projectDir := filepath.Join(t.TempDir(), "project")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	result, err := (&appImpl{}).Init(ctx, InitRequest{ProjectDir: projectDir, GenerateAIGuide: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.Success || len(result.Diagnostics) != 1 || result.Diagnostics[0].Code != codeInitCanceled {
		t.Fatalf("result = %#v, want %s", result, codeInitCanceled)
	}
	if _, err := os.Stat(projectDir); !os.IsNotExist(err) {
		t.Fatalf("canceled init left a Project directory; err=%v", err)
	}
}
